import type { SupportedLocale } from '@/i18n/types';

type LocalizedText = Record<SupportedLocale, string>;
export interface FaqItem { question: LocalizedText; answer: LocalizedText }
export interface FaqSection { id: string; title: LocalizedText; items: readonly FaqItem[] }

const faq = (enQuestion: string, enAnswer: string, esQuestion: string, esAnswer: string): FaqItem => ({
  question: { en: enQuestion, es: esQuestion },
  answer: { en: enAnswer, es: esAnswer },
});

export const FAQ_SECTIONS: readonly FaqSection[] = [
  {
    id: 'units-characteristics', title: { en: 'Units & Characteristics', es: 'Unidades y características' }, items: [
      faq('How do Shields work, and can they be healed?', 'A Unit’s Shield value is added directly to the Hit Points (HP) of its first model. For example, a Zealot (4 HP) with a Shield of 3 gives its first model a total of 7 HP. Lost HP from this combined pool can be healed normally.', '¿Cómo funcionan los Escudos y pueden curarse?', 'El valor de Escudo de una unidad se suma directamente a los Puntos de Vida (PV) de su primera miniatura. Por ejemplo, un Zealot (4 PV) con Escudo 3 proporciona a su primera miniatura un total de 7 PV. Los PV perdidos de esta reserva combinada pueden curarse con normalidad.'),
      faq('When exactly is SHIELDED Status lost?', 'SHIELDED Status is lost in either of the following two situations:\n• The Total Damage assigned to the Unit exceeds its Shield value. For example, a Unit with a Shield of 3 only loses its status after taking 4 or more damage, not 3. Because this is checked after damage is resolved, any abilities that reduce incoming damage before it is assigned can prevent the loss of SHIELDED Status.\n• The first model in the Unit is removed.\nOnce SHIELDED Status is lost, it cannot be restored by healing.', '¿Cuándo se pierde exactamente el estado SHIELDED?', 'El estado SHIELDED se pierde en cualquiera de estas dos situaciones:\n• El Daño Total asignado a la unidad supera su valor de Escudo. Por ejemplo, una unidad con Escudo 3 solo pierde el estado tras recibir 4 o más puntos de daño, no 3. Como esto se comprueba después de resolver el daño, las habilidades que reducen el daño entrante antes de asignarlo pueden evitar que se pierda SHIELDED.\n• Se retira la primera miniatura de la unidad.\nUna vez perdido, el estado SHIELDED no puede recuperarse mediante curación.'),
      faq('How does non-lethal damage interact with SHIELDED Status?', 'Non-lethal damage is added to the Unit’s Total Damage Pool and removes SHIELDED Status exactly like standard damage.', '¿Cómo interactúa el daño no letal con el estado SHIELDED?', 'El daño no letal se añade a la Reserva de Daño Total de la unidad y elimina el estado SHIELDED exactamente igual que el daño normal.'),
      faq('Can a destroyed Unit return to the game?', 'No. Once its last model is removed and a Unit is Destroyed, it cannot return to play. Unless specified otherwise in mission or other rules.', '¿Puede volver a la partida una unidad destruida?', 'No. Una vez retirada su última miniatura y Destruida la unidad, no puede volver al juego, salvo que una misión u otra regla indiquen lo contrario.'),
    ],
  },
  {
    id: 'measuring-movement', title: { en: 'Measuring & Movement', es: 'Medición y movimiento' }, items: [
      faq('How do you check if a Unit is Out of Coherency for the purpose of contesting objectives?', 'Unit Coherency is checked only at the end of a movement. If the Unit passed its last check, it remains in Coherency for objective control, regardless of any casualties suffered since then.', '¿Cómo se comprueba si una unidad está Fuera de Coherencia a la hora de disputar objetivos?', 'La Coherencia de Unidad solo se comprueba al final de un movimiento. Si la unidad superó su última comprobación, permanece en Coherencia para controlar objetivos, sin importar las bajas sufridas desde entonces.'),
      faq('Do Gap Clearance rules apply to gaps between models, or only to gaps in or between terrain?', 'They apply to both. A gap is defined as any physical space between terrain pieces or models through which a moving model’s base must pass.', '¿Las reglas de Espacio de Paso se aplican a huecos entre miniaturas o solo a huecos en el terreno o entre elementos de terreno?', 'Se aplican a ambos. Un hueco es cualquier espacio físico entre elementos de terreno o miniaturas por el que deba pasar la peana de una miniatura en movimiento.'),
      faq('Can models be placed on the other side of an enemy unit during a Charge or Close Ranks action, even if there are no gaps?', 'Yes. Coherency Links may pass through Enemy models that your Unit is currently Engaged with. As long as there is open space to place the bases within Coherency, models can be set on the other side of the enemy.', '¿Pueden colocarse miniaturas al otro lado de una unidad enemiga durante una acción de Carga o Close Ranks aunque no haya huecos?', 'Sí. Los Enlaces de Coherencia pueden atravesar miniaturas enemigas con las que tu unidad esté trabada. Siempre que haya espacio libre para colocar las peanas en Coherencia, las miniaturas pueden situarse al otro lado del enemigo.'),
      faq('Can a Coherency Link pass through terrain, models, and gaps that the Leading Model could move through, or only gaps?', 'It can pass through anything the Leading Model can legally traverse. For example, since Zerg Raptors have special movement rules allowing them to traverse IMPASSABLE TERRAIN, other models in the Unit can trace their Coherency Links directly through that terrain piece to stay connected.', '¿Puede un Enlace de Coherencia atravesar terreno, miniaturas y huecos por los que podría pasar la Miniatura Líder, o solo huecos?', 'Puede atravesar cualquier cosa que la Miniatura Líder pueda cruzar legalmente. Por ejemplo, como los Raptors Zerg tienen reglas especiales que les permiten atravesar IMPASSABLE TERRAIN, las demás miniaturas de la unidad pueden trazar sus Enlaces de Coherencia directamente a través de ese elemento para mantenerse conectadas.'),
      faq('Can I place a model onto High Ground from an Access Point using Coherency, or do I need to perform a Move action?', 'You can do so via Coherency, no separate Move action is required. When a Unit resolves a movement, only the nominated Leading Model measures and moves along a physical path. All other models in the Unit are set on the battlefield, and Coherency Links are explicitly allowed to trace through Access Points to connect models across different elevation levels.', '¿Puedo colocar una miniatura en Terreno Elevado desde un Punto de Acceso usando la Coherencia o necesito realizar una acción de Movimiento?', 'Puedes hacerlo mediante Coherencia; no hace falta una acción de Movimiento independiente. Cuando una unidad resuelve un movimiento, solo la Miniatura Líder designada mide y se desplaza por un recorrido físico. Las demás miniaturas se colocan en el campo de batalla y los Enlaces de Coherencia pueden trazarse expresamente a través de Puntos de Acceso para conectar miniaturas en distintos niveles de elevación.'),
      faq('With the Move or Run actions, can I move 0”?', 'No. A Unit must actually change its position on the battlefield when performing a Move or Run action. If a Unit does not reposition, it is considered to have performed a Hold action instead.', '¿Puedo mover 0” con las acciones de Movimiento o Carrera?', 'No. Una unidad debe cambiar realmente su posición en el campo de batalla al realizar una acción de Movimiento o Carrera. Si no se recoloca, se considera que ha realizado una acción de Mantener la Posición.'),
      faq('Does the Leading Model have to move its maximum distance during a “directly towards” or “directly away” move?', 'Yes. The Leading Model must move the maximum possible distance Directly Towards or Directly Away from the target, as applicable.', '¿Debe la Miniatura Líder recorrer su distancia máxima durante un movimiento «directamente hacia» o «directamente en dirección contraria»?', 'Sí. La Miniatura Líder debe mover la máxima distancia posible Directamente Hacia o Directamente en Dirección Contraria al objetivo, según corresponda.'),
      faq('What happens when a model cannot fit its base on High Ground?', 'Apply the Wobbly Model Syndrome rules. The centre of the model’s base must remain on the High Ground terrain feature, and the base may overhang the edge by the minimum amount necessary to stand.', '¿Qué ocurre cuando la peana de una miniatura no cabe en Terreno Elevado?', 'Aplica las reglas de Wobbly Model Syndrome. El centro de la peana debe permanecer sobre el elemento de Terreno Elevado y la peana puede sobresalir del borde lo mínimo necesario para mantenerse.'),
      faq('How do Gap Clearance checks work with High Ground, and can you move past a model that is less than an inch from its edge?', 'The edge of a High Ground feature is treated as Impassable Terrain for Gap Clearance purposes. Consequently, any physical space must satisfy the moving model’s Size requirement (1” wide for Size 2 or lower, and 3” wide for Size 3 or larger Units). For example, a Size 3 Siege Tank can drive up a ramp if the gap between the ramp’s edges is at least 3” wide, and it can be placed at the top using the Wobbly Model Syndrome rules if its base cannot fit entirely.', '¿Cómo funcionan las comprobaciones de Espacio de Paso con Terreno Elevado y se puede pasar junto a una miniatura situada a menos de una pulgada del borde?', 'El borde de un elemento de Terreno Elevado se considera Terreno Infranqueable a efectos de Espacio de Paso. Por tanto, todo espacio físico debe cumplir el requisito de Tamaño de la miniatura en movimiento: 1” de ancho para Tamaño 2 o inferior y 3” para unidades de Tamaño 3 o superior. Por ejemplo, un Siege Tank de Tamaño 3 puede subir por una rampa si el hueco entre sus bordes mide al menos 3”, y puede colocarse arriba usando Wobbly Model Syndrome si su peana no cabe por completo.'),
      faq('Can a Ground Unit move directly between unconnected High Grounds?', 'No. Ground Units can only move between connected High Grounds.', '¿Puede una unidad Terrestre moverse directamente entre zonas de Terreno Elevado no conectadas?', 'No. Las unidades Terrestres solo pueden moverse entre zonas de Terreno Elevado conectadas.'),
    ],
  },
  {
    id: 'battlefield', title: { en: 'The Battlefield', es: 'El campo de batalla' }, items: [
      faq('Can a model gain Direct Cover by being within 1” of any part of a terrain piece, even if that specific part is not between the model and the attacker, so long as the Line of Sight trace passes through that terrain?', 'Yes. Direct Cover is established as long as the Line of Sight trace passes through a terrain piece and the model is Within 1” of any part of that same terrain piece. It does not matter if the specific section of the terrain Within 1” is the part physically obstructing the trace.', '¿Puede una miniatura obtener Cobertura Directa por estar a 1” o menos de cualquier parte de un elemento de terreno, aunque esa parte concreta no esté entre ella y el atacante, siempre que la Línea de Visión atraviese ese terreno?', 'Sí. Hay Cobertura Directa si la Línea de Visión atraviesa un elemento de terreno y la miniatura está a 1” o menos de cualquier parte de ese mismo elemento. No importa que la sección situada a 1” o menos sea la que obstruye físicamente el trazado.'),
      faq('Can an objective marker be controlled while it is Deactivated?', 'Yes. Deactivated Mission Markers can still be controlled normally. The rules for determining control apply to all Mission Markers currently on the battlefield, regardless of whether they are flipped to their Activated or Deactivated side.', '¿Puede controlarse un marcador de objetivo mientras está Desactivado?', 'Sí. Los Marcadores de Misión Desactivados pueden controlarse con normalidad. Las reglas para determinar el control se aplican a todos los Marcadores de Misión presentes en el campo de batalla, estén por su lado Activado o Desactivado.'),
      faq('During the Mission and Deployment draft, when both players have the same card, do I remove a specific card or the card name?', 'You block only the specific physical card, not its name. Since players can bring identical cards, removing one physical copy from the table does not discard the duplicate copy, which remains a valid choice.', 'Durante el draft de Misión y Despliegue, si ambos jugadores tienen la misma carta, ¿se retira una carta concreta o el nombre de la carta?', 'Solo se bloquea la carta física concreta, no su nombre. Como los jugadores pueden llevar cartas idénticas, retirar una copia física de la mesa no descarta la copia duplicada, que sigue siendo una elección válida.'),
      faq('Are the long walls shown in the official map layouts treated as a single terrain feature or as multiple independent terrain pieces?', 'They are treated as multiple independent terrain pieces.', '¿Los muros largos de los mapas oficiales se consideran un único elemento de terreno o varios elementos independientes?', 'Se consideran varios elementos de terreno independientes.'),
      faq('Can a Flying or BURROWED Unit claim a Controlled Mission Marker in “Artefact Hunt”?', 'Yes. Rules blocking them from Controlling or Contesting Mission Markers do not prevent them from claiming said markers in the “Artefact Hunt”.', '¿Puede una unidad Voladora o BURROWED reclamar un Marcador de Misión Controlado en «Artefact Hunt»?', 'Sí. Las reglas que les impiden Controlar o Disputar Marcadores de Misión no les impiden reclamar esos marcadores en «Artefact Hunt».'),
    ],
  },
  {
    id: 'deployment', title: { en: 'Deployment, Entry Edges, & Zone of Influence', es: 'Despliegue, Bordes de Entrada y Zona de Influencia' }, items: [
      faq('If High Ground is touching the edge of the board, can a Unit deploy directly onto it?', 'Yes. Models may deploy directly onto High Ground if the player’s Entry Edge physically touches that terrain feature. All standard deployment requirements still apply, meaning the Unit must be placed legally in Coherency.', 'Si un Terreno Elevado toca el borde de la mesa, ¿puede una unidad desplegar directamente sobre él?', 'Sí. Las miniaturas pueden desplegar directamente sobre Terreno Elevado si el Borde de Entrada del jugador toca físicamente ese elemento. Se siguen aplicando todos los requisitos normales de despliegue, incluida la colocación legal en Coherencia.'),
      faq('Does the Omega Network’s ability count as a player’s Entry Edge for rules like Photon Overcharge?', 'Yes. Both the Omega Worm and a Pylon’s base are treated as friendly Entry Edges owned by the player who placed them.\n• Because they are Friendly Entry Edges, you can trigger abilities like Burrow Ambush from them, and they are immune to enemy denial effects like Photon Overcharge.\n• Standard forward-deployment cards and transports (e.g., Proxy Barrack, or Warp Prism) do not create Entry Edges. They simply grant a temporary exception to the rules to deploy without one.', '¿La habilidad Omega Network cuenta como Borde de Entrada de un jugador para reglas como Photon Overcharge?', 'Sí. Tanto el Omega Worm como la peana de un Pylon se consideran Bordes de Entrada amigos propiedad del jugador que los colocó.\n• Al ser Bordes de Entrada amigos, permiten activar habilidades como Burrow Ambush y son inmunes a efectos enemigos de denegación como Photon Overcharge.\n• Las cartas normales de despliegue avanzado y los transportes, como Proxy Barrack o Warp Prism, no crean Bordes de Entrada; solo conceden una excepción temporal para desplegar sin uno.'),
      faq('Can a Unit deployed through a Pylon as an Entry Edge perform any additional actions or resolve abilities?', 'No. Deploying a Unit this way consumes its entire Activation, which ends immediately upon setup. Once the Unit is placed on the battlefield, you must place an Activation Marker next to it, preventing it from performing any further actions or resolving any other active abilities during that Phase.', '¿Puede una unidad desplegada mediante un Pylon usado como Borde de Entrada realizar acciones adicionales o resolver habilidades?', 'No. Desplegar de este modo consume toda su Activación, que termina inmediatamente tras la colocación. Una vez situada en el campo de batalla, debes colocar junto a ella un Marcador de Activación, por lo que no puede realizar más acciones ni resolver otras habilidades activas durante esa Fase.'),
      faq('Does the Omega Network’s ability generate a Zone of Influence (the restricted area extending 6” from a player’s Entry Edge)?', 'No. Zones of Influence are only generated by the primary Entry Edges defined by your Deployment Card and are marked exclusively during battlefield setup.', '¿La habilidad Omega Network genera una Zona de Influencia?', 'No. Las Zonas de Influencia solo las generan los Bordes de Entrada principales definidos por tu Carta de Despliegue y se marcan exclusivamente durante la preparación del campo de batalla.'),
      faq('How does deployment work for end-of-round deployment abilities (like Ventral Sacs, Ready For Dust-off, or Warp Conduit) that place a Unit from a marker?', 'Place the leading model in base-to-base contact with the marker, and the remaining models in Unit Coherency completely outside of enemy Engagement Range. If you cannot place the leading model in base-to-base contact with the marker while keeping it outside of enemy Engagement Range, the Unit cannot be deployed, and the ability is wasted.', '¿Cómo funciona el despliegue de final de ronda mediante habilidades como Ventral Sacs, Ready For Dust-off o Warp Conduit, que colocan una unidad desde un marcador?', 'Coloca la Miniatura Líder en contacto peana con peana con el marcador y las restantes en Coherencia de Unidad, completamente fuera del Alcance de Enfrentamiento enemigo. Si no puedes colocar la Miniatura Líder en contacto con el marcador y fuera de dicho alcance, la unidad no puede desplegarse y la habilidad se pierde.'),
      faq('Can a Special Ability be used before deploying a Unit (e.g., triggering Stimpack to increase its Speed)?', 'No. Abilities do not function while a Unit is in Reserves. Only abilities that explicitly state they work in Reserves (such as “Raiders Roll!”) or those that actually deploy the Unit (like “Armed and Ready” or “Phase Prism”) can be resolved before deployment.', '¿Puede usarse una Habilidad Especial antes de desplegar una unidad, por ejemplo Stimpack para aumentar su Velocidad?', 'No. Las habilidades no funcionan mientras una unidad está en Reservas. Antes del despliegue solo pueden resolverse las que indiquen expresamente que funcionan en Reservas, como «Raiders Roll!», o las que despliegan realmente la unidad, como «Armed and Ready» o «Phase Prism».'),
      faq('What does “Nominated to deploy” mean?', 'This term refers to a Unit actively performing a Deploy Action. Any card effect, special ability, or core game rule that causes a Unit to perform a Deploy Action counts as that Unit being nominated to deploy.', '¿Qué significa «Nominated to deploy»?', 'Se refiere a una unidad que está realizando activamente una Acción de Despliegue. Cualquier efecto de carta, habilidad especial o regla básica que haga que una unidad realice esa acción cuenta como que la unidad ha sido designada para desplegar.'),
      faq('Can Units benefit from the Creep speed buff during their Deploy move?', 'No. Units in Reserves cannot use abilities or measure range until they are placed on the battlefield. Because a Unit’s passive abilities do not function while in Reserves and the Unit cannot be “On Creep” before actually entering the board, the Deploy must be resolved using the Unit’s standard Speed characteristic.', '¿Pueden las unidades beneficiarse del aumento de Velocidad del Creep durante su movimiento de Despliegue?', 'No. Las unidades en Reservas no pueden usar habilidades ni medir alcances hasta estar colocadas en el campo de batalla. Como sus habilidades pasivas no funcionan en Reservas y no pueden estar SOBRE CREEP antes de entrar, el Despliegue se resuelve usando su Velocidad normal.'),
    ],
  },
  {
    id: 'attack-sequence', title: { en: 'Attack Sequence', es: 'Secuencia de ataque' }, items: [
      faq('Do Evade rolls work against Surge?', 'Yes. Evade rolls are resolved against the final Damage Pool, which includes Surge. Surge only bypasses the Armour Roll, moving successful hits directly to the Damage Pool.', '¿Funcionan las tiradas de Evasión contra Surge?', 'Sí. Las tiradas de Evasión se resuelven contra la Reserva de Daño final, que incluye Surge. Surge solo evita la Tirada de Armadura y mueve los impactos exitosos directamente a la Reserva de Daño.'),
      faq('Can ANTI-EVADE (or any other modifier) ever negate an Evade roll (or any other check) entirely?', 'No. Target numbers can never be modified below 2+ or above 6+. Because abilities like ANTI-EVADE apply modifiers, they can only worsen a check to a maximum of 6+.', '¿Puede ANTI-EVADE, u otro modificador, anular por completo una tirada de Evasión u otra comprobación?', 'No. Los valores objetivo nunca pueden modificarse por debajo de 2+ ni por encima de 6+. Como ANTI-EVADE aplica modificadores, solo puede empeorar una comprobación hasta un máximo de 6+.'),
      faq('Can Ranged Attacks destroy target models that are outside of weapon range if they are within Line of Sight?', 'Yes. Casualty removal is restricted only by visibility, not range. Any model in the target Unit that is visible to at least one model in the attacking Unit is eligible to be removed as a casualty, even if that specific model is physically outside of the weapon’s range.', '¿Pueden los Ataques a Distancia destruir miniaturas objetivo fuera del alcance del arma si están en Línea de Visión?', 'Sí. La retirada de bajas solo está limitada por la visibilidad, no por el alcance. Cualquier miniatura de la unidad objetivo visible para al menos una miniatura atacante puede retirarse como baja, aunque esté físicamente fuera del alcance del arma.'),
      faq('When a Unit is engaged, and all of its models are in base-to-base contact, can you perform a Close Ranks action?', 'No. Since the action requires the Leading Model to end their movement closer to the enemy than they started, a Unit where everyone is already in base-to-base contact cannot resolve a Close Ranks action.', 'Si una unidad está trabada y todas sus miniaturas están en contacto peana con peana, ¿puede realizar una acción Close Ranks?', 'No. La acción exige que la Miniatura Líder termine más cerca del enemigo que al comenzar; una unidad cuyas miniaturas ya están todas en contacto peana con peana no puede resolverla.'),
      faq('How are models removed in close combat when fighting multiple enemy Units at once?', 'You must prioritise maintaining engagement with ALL enemy Units. When removing casualties at Priority 2 or 3, you cannot choose a model if its removal would break engagement with a specific enemy Unit, as long as another valid casualty exists in any priority tier.', '¿Cómo se retiran miniaturas en combate cuerpo a cuerpo cuando se lucha contra varias unidades enemigas a la vez?', 'Debes priorizar mantener el enfrentamiento con TODAS las unidades enemigas. Al retirar bajas de Prioridad 2 o 3, no puedes elegir una miniatura cuya retirada rompa el enfrentamiento con una unidad enemiga concreta mientras exista otra baja válida en cualquier nivel de prioridad.'),
      faq('When a Unit has multiple different ranged weapons, must you declare all targets before you begin rolling to hit?', 'No. Targets are declared and resolved one weapon Batch at a time. You select a target for your first weapon type, resolve those attacks completely, and only then declare the target for your next weapon type.', 'Cuando una unidad tiene varias armas a distancia diferentes, ¿deben declararse todos los objetivos antes de empezar a tirar para Impactar?', 'No. Los objetivos se declaran y resuelven Lote de arma por Lote de arma. Eliges el objetivo del primer tipo de arma, resuelves por completo esos ataques y solo entonces declaras el objetivo del siguiente tipo.'),
    ],
  },
  {
    id: 'abilities-tactics', title: { en: 'Abilities & Tactics Cards', es: 'Habilidades y Cartas Tácticas' }, items: [
      faq('How do CP, BM, and PE resources work when paying for special abilities?', 'You must exhaust (flip face-down) one or more Ready cards matching the required resource type to pay the cost. Any excess resources generated are lost and cannot be saved or spent on another ability. For example, exhausting a card that produces 2 CP to pay for a 1 CP ability immediately discards the leftover 1 CP.', '¿Cómo funcionan los recursos CP, BM y PE al pagar Habilidades Especiales?', 'Debes Agotar, poniéndolas boca abajo, una o más cartas Ready del tipo de recurso requerido. Todo excedente se pierde y no puede guardarse ni gastarse en otra habilidad. Por ejemplo, Agotar una carta que produce 2 CP para pagar una habilidad de 1 CP descarta inmediatamente el CP sobrante.'),
      faq('Is a Unit considered within range of itself for its own abilities?', 'Yes. A Unit is always considered within range of itself unless a rule explicitly states otherwise.', '¿Se considera que una unidad está dentro del alcance de sus propias habilidades?', 'Sí. Una unidad siempre se considera dentro del alcance de sí misma salvo que una regla indique expresamente lo contrario.'),
      faq('Does activating a Tactical Card to use one of its abilities require an active Unit on the battlefield, even if the card doesn’t directly affect that Unit?', 'Yes. An active Unit on the battlefield is always required to resolve a card’s Active Ability.', '¿Activar una Carta Táctica exige una unidad activa en el campo de batalla aunque la carta no la afecte directamente?', 'Sí. Siempre se necesita una unidad activa en el campo de batalla para resolver la Habilidad Activa de una carta.'),
      faq('Can a Unit use any number of Active abilities or Tactical Cards during its Activation?', 'Yes. A Unit can resolve any number of differently named Active abilities or Tactical Cards during its Activation, provided you can pay their resource costs. However, Reactions are restricted to one per Activation. Named Active abilities cannot be used more than Once per Round per Unit unless a rule explicitly states otherwise (e.g., a single Marine Unit cannot trigger the “Go! Go! Go!” ability twice in the same Round).', '¿Puede una unidad usar cualquier número de habilidades Activas o Cartas Tácticas durante su Activación?', 'Sí. Puede resolver cualquier número de habilidades Activas o Cartas Tácticas con nombres distintos si puede pagar sus costes. Sin embargo, las Reacciones están limitadas a una por Activación. Una habilidad Activa con nombre no puede usarse más de Una vez por Ronda por unidad salvo indicación expresa; por ejemplo, una unidad de Marines no puede activar «Go! Go! Go!» dos veces en la misma Ronda.'),
      faq('When resolving the Marauder’s Concussive Shells reaction, do you need Line of Sight to the charging Enemy Unit or to the Friendly Unit being charged?', 'You only need Line of Sight to the Friendly Unit. Because the ability is measured and targeted toward a Friendly Unit Within 8”, that friendly unit is the subject of the range and visibility check.', 'Al resolver la reacción Concussive Shells del Marauder, ¿se necesita Línea de Visión hacia la unidad enemiga que carga o hacia la unidad amiga cargada?', 'Solo necesitas Línea de Visión hacia la unidad amiga. Como la habilidad se mide y dirige a una unidad amiga a 8” o menos, esa unidad es el sujeto de la comprobación de alcance y visibilidad.'),
      faq('Can Raptors stack the IMPACT modifiers from Malignant Creep, the Evolution Chamber, and their Adrenal Overload ability?', 'Yes. Because these abilities apply numeric modifiers rather than keywords, they stack. Modifiers from different named sources are cumulative, allowing these three effects to combine for a potential +3 bonus.', '¿Pueden los Raptors acumular los modificadores de IMPACT de Malignant Creep, Evolution Chamber y Adrenal Overload?', 'Sí. Como aplican modificadores numéricos en lugar de keywords, se acumulan. Los modificadores de fuentes con nombres distintos son acumulativos, por lo que los tres efectos pueden combinarse para un posible +3.'),
      faq('Can you stack Accelerating Creep with the Queen’s Creep Speed, Wild Mutation, or Roach Glial Reconstitution?', 'Movement modifiers from different named sources stack normally, unless they share the BUFF keyword. Because Accelerating Creep and the Queen’s Creep Speed upgrade apply flat modifiers without using keywords, they stack with other speed bonuses. However, both Wild Mutation and Glial Reconstitution grant the BUFF Speed keyword, meaning they do not stack with each other.', '¿Puede acumularse Accelerating Creep con Creep Speed de la Queen, Wild Mutation o Glial Reconstitution del Roach?', 'Los modificadores de movimiento de fuentes con nombres distintos se acumulan salvo que compartan la keyword BUFF. Accelerating Creep y Creep Speed aplican modificadores planos y se acumulan con otros bonos de Velocidad. Wild Mutation y Glial Reconstitution conceden BUFF Speed, por lo que no se acumulan entre sí.'),
      faq('Can an opponent place their models on a Faction Indicator (from Ventral Sacs, Ready For Dust-off, or Warp Conduit)?', 'Yes. Opponents can freely move onto and block a Faction Indicator. If the indicator becomes blocked so that you can no longer place a deploying model in base-to-base contact with it, the indicator remains on the field until the End of the Round and is then removed without deploying the Unit.', '¿Puede un oponente colocar sus miniaturas sobre un Indicador de Facción de Ventral Sacs, Ready For Dust-off o Warp Conduit?', 'Sí. Los oponentes pueden moverse libremente sobre él y bloquearlo. Si queda bloqueado y ya no puede colocarse una miniatura en despliegue en contacto peana con peana, permanece hasta el Final de la Ronda y después se retira sin desplegar la unidad.'),
      faq('How do you resolve the PLACE (0) effect of Artanis’s Phase Prism ability?', 'Place Artanis directly in base-to-base contact with a model in the selected target Unit.', '¿Cómo se resuelve el efecto PLACE (0) de Phase Prism de Artanis?', 'Coloca a Artanis directamente en contacto peana con peana con una miniatura de la unidad objetivo seleccionada.'),
      faq('Can damage already assigned to a Unit be removed?', 'Yes. Damage reduction applies to a Unit’s Total Damage (the sum of existing and newly assigned damage). For example, if a Marauder Unit with 2 damage takes 1 additional damage, a Medic’s “Life Support” can remove all 3 damage.', '¿Puede retirarse daño ya asignado a una unidad?', 'Sí. La reducción de daño se aplica al Daño Total de la unidad, sumando el existente y el recién asignado. Por ejemplo, si una unidad Marauder con 2 de daño recibe 1 adicional, «Life Support» de un Medic puede retirar los 3.'),
      faq('Can Roaches move through a Force Field using Tunnelling Claws?', 'No. Tunnelling Claws only allow a Unit to move through enemy Units, not Terrain. Since a Force Field is classified as Terrain, it cannot be bypassed or moved through using this ability.', '¿Pueden los Roaches atravesar un Force Field usando Tunnelling Claws?', 'No. Tunnelling Claws solo permite atravesar unidades enemigas, no Terreno. Como Force Field se clasifica como Terreno, esta habilidad no permite evitarlo ni atravesarlo.'),
      faq('Can a Size 3 Unit be PLACED into a Force Field to automatically remove it?', 'No. Because a PLACE effect is not a movement, it cannot remove a Force Field.', '¿Puede una unidad de Tamaño 3 ser PLACED dentro de un Force Field para retirarlo automáticamente?', 'No. Como un efecto PLACE no es un movimiento, no puede retirar un Force Field.'),
      faq('Can Raptors move across Force Fields, since they can normally bypass terrain?', 'No. Force Fields explicitly forbid Units of Size 2 or less from moving across them. Because Raptors are Size 1, they cannot ignore this specific terrain restriction.', '¿Pueden los Raptors atravesar Force Fields dado que normalmente pueden evitar el terreno?', 'No. Force Fields prohíbe expresamente que las unidades de Tamaño 2 o inferior los atraviesen. Como los Raptors son de Tamaño 1, no pueden ignorar esta restricción específica.'),
      faq('When is ON CREEP checked for the movement bonus from Accelerating Creep?', 'At the start of the movement. If a Unit is ON CREEP when it begins its movement, it gains the bonus for the entire move, even if it leaves Creep during that movement.', '¿Cuándo se comprueba SOBRE CREEP para el bono de movimiento de Accelerating Creep?', 'Al comienzo del movimiento. Si una unidad está SOBRE CREEP al iniciarlo, obtiene el bono durante todo el movimiento aunque salga del Creep.'),
      faq('Can you use the Advanced Training reaction from the Academy if the card is already exhausted?', 'No. Once a Tactical Card is Exhausted, none of its printed abilities can be resolved or used until the card is Refreshed during the Phase 4 Cleanup.', '¿Puede usarse la reacción Advanced Training de Academy si la carta ya está Agotada?', 'No. Una vez Agotada una Carta Táctica, ninguna de sus habilidades impresas puede resolverse ni usarse hasta que la carta se Refresque durante la Limpieza de la Fase 4.'),
      faq('Can you resolve Reaction Abilities outside of an activation?', 'Yes. Reactions can be resolved at any time their specific trigger conditions are met, regardless of whether a Unit is currently activated.\n• Outside of activations, you are restricted to resolving only one Reaction per trigger (provided the participating Unit has not already used that reaction this round).\n• If both players attempt to react to the same trigger outside of an activation, the holder of the First Player Marker resolves theirs first.', '¿Pueden resolverse Habilidades de Reacción fuera de una Activación?', 'Sí. Las Reacciones pueden resolverse cuando se cumplan sus condiciones de activación, haya o no una unidad activada.\n• Fuera de las Activaciones solo puede resolverse una Reacción por desencadenante, siempre que la unidad participante no haya usado ya esa reacción esta ronda.\n• Si ambos jugadores reaccionan al mismo desencadenante fuera de una Activación, resuelve primero quien tenga el Marcador de Primer Jugador.'),
      faq('What counts as targeting a Structure?', 'Abilities can affect a Structure if they target an area or the Unit itself rather than a specific individual model. Structures are only excluded from an ability’s effects if that ability’s targeting requirements, keywords, or restrictions rule them out.', '¿Qué cuenta como tener una Estructura como objetivo?', 'Las habilidades pueden afectar a una Estructura si tienen como objetivo un área o la propia unidad en lugar de una miniatura concreta. Las Estructuras solo quedan excluidas si los requisitos de objetivo, keywords o restricciones de la habilidad así lo indican.'),
      faq('What is the difference between “select” and “target”?', 'There is no mechanical or rules distinction between these two terms. They are treated as synonyms.', '¿Qué diferencia hay entre «select» y «target»?', 'No existe ninguna diferencia mecánica ni reglamentaria entre ambos términos. Se consideran sinónimos.'),
      faq('Can an Adept Unit use Psionic Transfer to “teleport” while carrying a claimed Mission Marker in the “Artefact Hunt” mission?', 'No.', '¿Puede una unidad Adept usar Psionic Transfer para «teletransportarse» mientras transporta un Marcador de Misión reclamado en «Artefact Hunt»?', 'No.'),
    ],
  },
  {
    id: 'keywords', title: { en: 'Keywords', es: 'Keywords' }, items: [
      faq('Does PINPOINT allow a Unit to ignore its own engagement and shoot at outside targets, or does it only allow targeting an engaged enemy?', 'It only allows shooting into combat, not shooting out of it. The keyword overrides the targeting restriction on the target Unit, allowing models to shoot at Engaged enemies.', '¿Permite PINPOINT ignorar el propio enfrentamiento y disparar a objetivos externos o solo apuntar a un enemigo trabado?', 'Solo permite disparar hacia un combate, no desde él hacia fuera. La keyword anula la restricción de objetivo de la unidad objetivo y permite disparar a enemigos Trabados.'),
      faq('Can I remove a Creep Token by using the PLACE keyword?', 'No. Creep Removal only triggers when an enemy Unit ends a Move, Deploy, Run, Charge, or Disengage action within 1” of a Creep Tumor. As PLACE is neither of those, ending a PLACE movement near a Creep Tumor does not remove it.', '¿Puedo retirar una ficha de Creep usando la keyword PLACE?', 'No. Creep Removal solo se activa cuando una unidad enemiga termina una acción de Movimiento, Despliegue, Carrera, Carga o Desenganche a 1” o menos de un Creep Tumor. PLACE no es ninguna de ellas y no lo retira.'),
      faq('To benefit from the LOCKED IN keyword, must the attacking model be stationary, or does the target need to have Stationary Status?', 'The target must have the Stationary Status.', 'Para beneficiarse de LOCKED IN, ¿debe estar inmóvil la miniatura atacante o debe tener el objetivo el estado Stationary?', 'El objetivo debe tener el estado Stationary.'),
      faq('How does Indirect Fire work against a target Unit when only some of its models are visible?', 'The target Unit does not gain an Evade roll, and non-visible models can still be removed as casualties. Because at least one model is visible, the target Unit itself is considered to be within Line of Sight, meaning it does not qualify for the Evade roll granted to out-of-sight targets.', '¿Cómo funciona Indirect Fire contra una unidad objetivo cuando solo algunas de sus miniaturas son visibles?', 'La unidad objetivo no obtiene tirada de Evasión y las miniaturas no visibles pueden retirarse como bajas. Al ser visible al menos una miniatura, la unidad se considera dentro de Línea de Visión y no cumple el requisito para la Evasión concedida a objetivos fuera de visión.'),
      faq('Since HIDDEN Units cannot be targeted from more than 4” away, how can “detection” abilities (such as Scanner Sweep, Oversight Mode, or Surveillance) affect them at a 6” range?', 'These abilities target a location on the battlefield rather than the Units themselves. They place a Faction Indicator to create a 6” area of effect. Because the ability does not select the Unit as a target, it bypasses the 4” targeting restriction.', 'Si las unidades HIDDEN no pueden ser objetivo desde más de 4”, ¿cómo pueden afectarles habilidades de detección como Scanner Sweep, Oversight Mode o Surveillance a 6”?', 'Estas habilidades tienen como objetivo una ubicación del campo de batalla, no las unidades. Colocan un Indicador de Facción que crea un área de efecto de 6”. Como no seleccionan la unidad como objetivo, evitan la restricción de 4”.'),
      faq('When are abilities or effects with a “while within” condition checked?', 'These effects are checked at the start and the end of any action or ability during the game round. If a Unit is within the specified range and meets all other requirements, the effect applies immediately.', '¿Cuándo se comprueban las habilidades o efectos con una condición «while within»?', 'Al principio y al final de cualquier acción o habilidad durante la ronda. Si una unidad está dentro del alcance indicado y cumple los demás requisitos, el efecto se aplica inmediatamente.'),
      faq('Can a Reaction ability with the REPEATABLE keyword be used multiple times during the same Activation?', 'No. The standard limit of one Reaction per Activation still applies. While REPEATABLE allows the ability to be used across different Activations during the round, it cannot be used multiple times in the same Activation. For triggers that occur outside of an Activation entirely, the ability can only be used once per trigger.', '¿Puede usarse varias veces durante la misma Activación una Reacción con REPEATABLE?', 'No. Sigue aplicándose el límite de una Reacción por Activación. REPEATABLE permite usarla en distintas Activaciones de la ronda, no varias veces en la misma. Para desencadenantes completamente fuera de una Activación, solo puede usarse una vez por desencadenante.'),
      faq('Do keywords like PRECISION, SURGE, or CRITICAL HIT apply to individual models, or do they apply to the entire Unit?', 'They apply to the weapon Batch (the collective dice pool generated by the Unit’s attack) rather than to individual models. Models in a Unit using the same weapon profile combine their Rate of Attack (RoA) dice into a single pool, and these keywords act on the dice within that pool. Individual models are tracked separately only to determine Range, visibility, and specific per-model roll modifiers (such as the -1 Hit penalty for Long Range).', '¿Keywords como PRECISION, SURGE o CRITICAL HIT se aplican a miniaturas individuales o a toda la unidad?', 'Se aplican al Lote de arma, la reserva colectiva de dados generada por el ataque de la unidad, no a miniaturas individuales. Las miniaturas con el mismo perfil de arma combinan sus dados de Cadencia de Ataque en una sola reserva y las keywords actúan sobre ella. Solo se siguen por separado para determinar Alcance, visibilidad y modificadores concretos por miniatura, como el -1 a Impactar por Largo Alcance.'),
      faq('How do abilities like PRECISION work when splitting attacks in combat against multiple enemy Units?', 'Splitting attacks is resolved as a single Batch, allowing you to allocate keyword effects as they are resolved. Because the attacks against both Units occur simultaneously, you can choose to apply keywords like PRECISION entirely to one target’s pool or split them across both pools.', '¿Cómo funcionan habilidades como PRECISION al dividir ataques en combate contra varias unidades enemigas?', 'La división de ataques se resuelve como un único Lote, lo que permite asignar los efectos de las keywords al resolverlos. Como los ataques contra ambas unidades ocurren simultáneamente, puedes aplicar PRECISION por completo a una reserva objetivo o dividirla entre ambas.'),
      faq('Does morphing a Unit award Victory Points (VPs) to the opponent if the original Unit’s Supply Value is reduced?', 'Yes. Anytime a Unit’s Current Supply Value is reduced, including during a Morph, the opponent gains Victory Points (VPs) equal to the amount of Supply lost.', '¿Transformar una unidad concede PV al oponente si se reduce el Suministro de la unidad original?', 'Sí. Siempre que se reduce el Suministro Actual de una unidad, también durante un Morph, el oponente obtiene tantos PV como Suministro se haya perdido.'),
      faq('Does a MORPHED Unit award Victory Points (VPs) to the opponent when the Units’ Supply Value is reduced?', 'Yes. A MORPHED Unit awards Victory Points (VPs) exactly like any other Unit on the battlefield, equal to the amount of Supply lost.', '¿Concede una unidad MORPHED PV al oponente cuando se reduce su Suministro?', 'Sí. Una unidad MORPHED concede PV igual que cualquier otra unidad del campo de batalla: tantos como Suministro haya perdido.'),
      faq('If a Specialist model (like an AGG-12 Marine) is removed, can you keep the weapon in play by replacing another model that doesn’t have it?', 'No. You cannot transfer Specialist models to other models or replace a model without the weapon to keep the Specialist.', 'Si se retira una miniatura Especialista, como un Marine AGG-12, ¿puede mantenerse el arma sustituyendo otra miniatura que no la tenga?', 'No. No puedes transferir Especialistas a otras miniaturas ni sustituir una miniatura sin el arma para conservar al Especialista.'),
    ],
  },
  {
    id: 'templates-spillover', title: { en: 'Templates & Spillover', es: 'Plantillas y Spillover' }, items: [
      faq('How do Blast Template abilities (like Psionic Storm or Plague) resolve without a physical “Primary Target” to establish a Target Point, Elevation Level, or Combat Tags?', 'You resolve them using the template rules with the following key adaptations:\n• The Unit executing the ability is treated as the Attacking Model.\n• The point directly beneath the centre of the template is treated as the Target Point and the Primary Target.\n• Because this Target Point has no Combat Tags, spillover targets do not need to match any targeting tags to be affected.\n• Affected models must still occupy the same Elevation Level as the Target Point. For these attacks, Flying Units are treated as occupying the same Elevation Level as their physical bases on the battlefield.', '¿Cómo se resuelven las habilidades con Plantilla de Explosión, como Psionic Storm o Plague, sin un Objetivo Principal físico que determine Punto Objetivo, Elevación o Etiquetas de Combate?', 'Usa las reglas de plantillas con estas adaptaciones:\n• La unidad que ejecuta la habilidad se considera la Miniatura Atacante.\n• El punto justo debajo del centro de la plantilla se considera Punto Objetivo y Objetivo Principal.\n• Como no tiene Etiquetas de Combate, los objetivos de Spillover no necesitan coincidir con ninguna etiqueta para resultar afectados.\n• Las miniaturas afectadas deben ocupar el mismo Nivel de Elevación que el Punto Objetivo. En estos ataques, las unidades Voladoras se consideran en el mismo nivel que sus peanas físicas.'),
      faq('Does the Spillover requirement to “share the same Combat Tag as the Primary target” prevent a template from spilling over to models with different tags (e.g., from Light Zerglings to Armoured Roaches), or is it only meant to check Ground vs. Flying status?', 'Spillover targets only need to share at least one Combat Tag and match the elevation level of the Primary target. Since Zerglings and Roaches both share the Ground Combat Tags, a template can spill over between them if they are on the same elevation. Mutalisks cannot be affected by Ground-level templates even though they share the Biological tag, because Flying Units do not occupy a standard Elevation Level for template purposes.', '¿El requisito de Spillover de compartir la misma Etiqueta de Combate que el Objetivo Principal impide afectar a miniaturas con etiquetas diferentes, por ejemplo de Zerglings Light a Roaches Armoured, o solo comprueba Terrestre frente a Volador?', 'Los objetivos de Spillover solo necesitan compartir al menos una Etiqueta de Combate y el nivel de elevación del Objetivo Principal. Zerglings y Roaches comparten Ground, por lo que una plantilla puede pasar entre ellos si están en la misma elevación. Los Mutalisks no pueden verse afectados por plantillas a nivel del suelo aunque compartan Biological, porque las unidades Voladoras no ocupan un Nivel de Elevación normal a estos efectos.'),
      faq('How does Guardian Shield interact with Spillover?', 'Because Spillover hits are resolved as separate attack batches, the Guardian Shield modifier applies to each batch individually. Any Ranged Attack (including both the main target and any Spillover batches) targeting a friendly Unit affected by the Guardian Shield is made with 1 fewer die in its Attack Pool.', '¿Cómo interactúa Guardian Shield con Spillover?', 'Como los impactos de Spillover se resuelven en lotes de ataque separados, el modificador de Guardian Shield se aplica individualmente a cada lote. Todo Ataque a Distancia contra una unidad amiga afectada por Guardian Shield, tanto el objetivo principal como los lotes de Spillover, se realiza con 1 dado menos en su Reserva de Ataque.'),
      faq('How do keywords such as PRECISION (X) or CRITICAL HIT (X) interact with Spillover?', 'Weapon keywords apply exclusively to the Attack Pool generated against the Main Target. They do not carry over to Spillover batches, which are resolved as separate, basic attack batches without modifiers.', '¿Cómo interactúan keywords como PRECISION (X) o CRITICAL HIT (X) con Spillover?', 'Las keywords del arma se aplican exclusivamente a la Reserva de Ataque generada contra el Objetivo Principal. No se trasladan a los lotes de Spillover, que se resuelven como lotes de ataque básicos separados y sin modificadores.'),
    ],
  },
] as const;
